import type {Metadata} from "next";
import {Inter as FontSans} from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils";
import SideNavbar from "@/components/SideNavBar";

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
})
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={cn(
                "min-h-screen w-full bg-white text-black flex font-sans antialiased",
                fontSans.variable
            )}
        >
        <SideNavbar/>
        <div className="p-8 w-full">
            {children}
        </div>
        </body>
        </html>
    );
}
